from config.config import (
    get_settings,
    get_mcp_config,
    update_settings,
    update_mcp,
    get_model_name,
    get_openai_api_key,
    get_streaming,
    get_temperature,
    get_max_tokens,
    get_openrouter_api_key,
    get_openrouter_api_url,
    get_agentkube_server_url,
    get_user_rules,
    get_cluster_rules,
    get_kubeignore,
    update_user_rules,
    update_cluster_rules,
    update_kubeignore,
    get_deny_list,
    get_web_search_enabled,
    get_cluster_config,
    # Legacy provider functions (kept for backward compat during transition)
    is_custom_openai_enabled,
    get_custom_openai_key,
    get_custom_openai_base_url,
    is_custom_anthropic_enabled,
    get_custom_anthropic_key,
    is_custom_google_enabled,
    get_custom_google_key,
    is_azure_enabled,
    get_azure_config,
    is_ollama_enabled,
    get_ollama_endpoint,
    is_vllm_enabled,
    get_vllm_endpoint,
    # Agent model mapping
    get_agent_model_mapping,
    get_agent_model_config,
    # New generic provider functions (models.dev approach)
    get_provider_config,
    get_provider_api_key,
    get_provider_base_url,
    is_provider_enabled,
    get_enabled_model_ids,
    set_enabled_model_ids,
    connect_provider,
    disconnect_provider,
    config_manager
)
from config.setup import setup_config_directory

__all__ = [
    'setup_config_directory',
    'get_settings',
    'get_mcp_config',
    'update_settings',
    'update_mcp',
    'get_model_name',
    'get_openai_api_key',
    'get_streaming',
    'get_temperature',
    'get_max_tokens',
    'get_agentkube_server_url',
    'get_user_rules',
    'get_cluster_rules',
    'get_kubeignore',
    'update_user_rules',
    'update_cluster_rules',
    'update_kubeignore',
    'get_deny_list',
    'get_web_search_enabled',
    'get_cluster_config',
    # Legacy (kept for backward compat)
    'get_openrouter_api_key',
    'get_openrouter_api_url',
    'is_custom_openai_enabled',
    'get_custom_openai_key',
    'get_custom_openai_base_url',
    'is_custom_anthropic_enabled',
    'get_custom_anthropic_key',
    'is_custom_google_enabled',
    'get_custom_google_key',
    'is_azure_enabled',
    'get_azure_config',
    'is_ollama_enabled',
    'get_ollama_endpoint',
    'is_vllm_enabled',
    'get_vllm_endpoint',
    # Agent model mapping
    'get_agent_model_mapping',
    'get_agent_model_config',
    # New generic provider functions (models.dev)
    'get_provider_config',
    'get_provider_api_key',
    'get_provider_base_url',
    'is_provider_enabled',
    'get_enabled_model_ids',
    'set_enabled_model_ids',
    'connect_provider',
    'disconnect_provider',
    'config_manager'
]
