FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lockb ./
RUN bun install 

COPY . .
RUN bunx prisma generate

ENV NODE_ENV=production \
    DATABASE_URL=$DATABASE_URL \
    APP_URL=$APP_URL \
    DOCUSIGN_BASE_URL=$DOCUSIGN_BASE_URL \
    DOCUSIGN_INTEGRATION_KEY=$DOCUSIGN_INTEGRATION_KEY \
    DOCUSIGN_IMPERSONATED_USER_ID=$DOCUSIGN_IMPERSONATED_USER_ID \
    DOCUSIGN_SECRET_KEY=$DOCUSIGN_SECRET_KEY \
    POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    POSTGRES_DB=$POSTGRES_DB \
    POSTGRES_USER=$POSTGRES_USER \
    ENCRYPTION_KEY=$ENCRYPTION_KEY \
    LLM_PROVIDER=$LLM_PROVIDER \
    OPENAI_MODEL_NAME=$OPENAI_MODEL_NAME \
    OPENAI_API_KEY=$OPENAI_API_KEY \
    QDRANT_URL=$QDRANT_URL \
    REDIS_HOST=$REDIS_HOST \
    REDIS_PORT=$REDIS_PORT \
    REDIS_URL=$REDIS_URL

EXPOSE 8765

CMD ["bun", "run", "src/index.ts"]