export const AUDIT_ACTIONS = {
  // Resource actions
  RESOURCE_APPLIED: 'RESOURCE_APPLIED',
  RESOURCE_DELETED: 'RESOURCE_DELETED',
  
  // Investigation actions
  INVESTIGATION_CREATED: 'INVESTIGATION_CREATED',
  
  // API Key actions
  API_KEY_CREATED: 'API_KEY_CREATED',
  
  // Cluster actions
  CLUSTER_REGISTERED: 'CLUSTER_REGISTERED',
  CLUSTER_UPDATED: 'CLUSTER_UPDATED',
  CLUSTER_REMOVED: 'CLUSTER_REMOVED'
} as const;