export const CommandSuggestionsConstants = [
  // Get commands
  { command: 'kubectl get deployments' },
  { command: 'kubectl get pods' },
  { command: 'kubectl get services' },
  { command: 'kubectl get nodes' },
  { command: 'kubectl get daemonsets' },
  { command: 'kubectl get statefulsets' },
  { command: 'kubectl get replicasets' },
  { command: 'kubectl get jobs' },
  { command: 'kubectl get cronjobs' },
  { command: 'kubectl get configmaps' },
  { command: 'kubectl get secrets' },
  { command: 'kubectl get resourcequotas' },
  { command: 'kubectl get limitranges' },
  { command: 'kubectl get hpa' },
  { command: 'kubectl get vpa' },
  { command: 'kubectl get services' },
  { command: 'kubectl get ingresses' },
  { command: 'kubectl get endpoints' },
  { command: 'kubectl get networkpolicies' },
  { command: 'kubectl get pv' },
  { command: 'kubectl get pvc' },
  { command: 'kubectl get storageclasses' },
  { command: 'kubectl get namespaces' },
  { command: 'kubectl get events' },
  { command: 'kubectl get serviceaccounts' },
  { command: 'kubectl get roles' },
  { command: 'kubectl get rolebindings' },
  { command: 'kubectl get clusterroles' },
  { command: 'kubectl get clusterrolebindings' },
  { command: 'kubectl get crds' },
  
  // Describe commands
  { command: 'kubectl describe deployments' },
  { command: 'kubectl describe pods' },
  { command: 'kubectl describe services' },
  { command: 'kubectl describe nodes' },
  { command: 'kubectl describe daemonsets' },
  { command: 'kubectl describe statefulsets' },
  { command: 'kubectl describe replicasets' },
  { command: 'kubectl describe jobs' },
  { command: 'kubectl describe cronjobs' },
  { command: 'kubectl describe configmaps' },
  { command: 'kubectl describe secrets' },
  { command: 'kubectl describe resourcequotas' },
  { command: 'kubectl describe limitranges' },
  { command: 'kubectl describe hpa' },
  { command: 'kubectl describe vpa' },
  { command: 'kubectl describe ingresses' },
  { command: 'kubectl describe endpoints' },
  { command: 'kubectl describe networkpolicies' },
  { command: 'kubectl describe pv' },
  { command: 'kubectl describe pvc' },
  { command: 'kubectl describe storageclasses' },
  { command: 'kubectl describe namespaces' },
  { command: 'kubectl describe events' },
  { command: 'kubectl describe serviceaccounts' },
  { command: 'kubectl describe roles' },
  { command: 'kubectl describe rolebindings' },
  { command: 'kubectl describe clusterroles' },
  { command: 'kubectl describe clusterrolebindings' },
  { command: 'kubectl describe crds' },
  
  // Logs command (only for pods)
  // { command: 'kubectl logs <pod-name>' },
  // { command: 'kubectl logs <pod-name> -f' },
];
