export const CommandSuggestionsConstants = [
  // Get commands
  { command: 'kubectl get deployments' },
  { command: 'kubectl get pods' },
  { command: 'kubectl get services' },
  { command: 'kubectl get nodes' },
  { command: 'kubectl get daemonsets' },
  { command: 'kubectl get statefulsets' },
  { command: 'kubectl get replicasets' },
  { command: 'kubectl get jobs' },
  { command: 'kubectl get cronjobs' },
  { command: 'kubectl get configmaps' },
  { command: 'kubectl get secrets' },
  { command: 'kubectl get resourcequotas' },
  { command: 'kubectl get limitranges' },
  { command: 'kubectl get hpa' },
  { command: 'kubectl get vpa' },
  { command: 'kubectl get services' },
  { command: 'kubectl get ingresses' },
  { command: 'kubectl get endpoints' },
  { command: 'kubectl get networkpolicies' },
  { command: 'kubectl get pv' },
  { command: 'kubectl get pvc' },
  { command: 'kubectl get storageclasses' },
  { command: 'kubectl get namespaces' },
  { command: 'kubectl get events' },
  { command: 'kubectl get serviceaccounts' },
  { command: 'kubectl get roles' },
  { command: 'kubectl get rolebindings' },
  { command: 'kubectl get clusterroles' },
  { command: 'kubectl get clusterrolebindings' },
  { command: 'kubectl get crds' },
  // Get commands with --all-namespaces
  { command: 'kubectl get deployments --all-namespaces' },
  { command: 'kubectl get pods --all-namespaces' },
  { command: 'kubectl get services --all-namespaces' },
  { command: 'kubectl get daemonsets --all-namespaces' },
  { command: 'kubectl get statefulsets --all-namespaces' },
  { command: 'kubectl get replicasets --all-namespaces' },
  { command: 'kubectl get jobs --all-namespaces' },
  { command: 'kubectl get cronjobs --all-namespaces' },
  { command: 'kubectl get configmaps --all-namespaces' },
  { command: 'kubectl get secrets --all-namespaces' },
  { command: 'kubectl get resourcequotas --all-namespaces' },
  { command: 'kubectl get limitranges --all-namespaces' },
  { command: 'kubectl get hpa --all-namespaces' },
  { command: 'kubectl get vpa --all-namespaces' },
  { command: 'kubectl get ingresses --all-namespaces' },
  { command: 'kubectl get endpoints --all-namespaces' },
  { command: 'kubectl get networkpolicies --all-namespaces' },
  { command: 'kubectl get pvc --all-namespaces' },
  { command: 'kubectl get events --all-namespaces' },
  { command: 'kubectl get serviceaccounts --all-namespaces' },
  { command: 'kubectl get roles --all-namespaces' },
  { command: 'kubectl get rolebindings --all-namespaces' },
 // Describe commands
  { command: 'kubectl describe deployments' },
  { command: 'kubectl describe pods' },
  { command: 'kubectl describe services' },
  { command: 'kubectl describe nodes' },
  { command: 'kubectl describe daemonsets' },
  { command: 'kubectl describe statefulsets' },
  { command: 'kubectl describe replicasets' },
  { command: 'kubectl describe jobs' },
  { command: 'kubectl describe cronjobs' },
  { command: 'kubectl describe configmaps' },
  { command: 'kubectl describe secrets' },
  { command: 'kubectl describe resourcequotas' },
  { command: 'kubectl describe limitranges' },
  { command: 'kubectl describe hpa' },
  { command: 'kubectl describe vpa' },
  { command: 'kubectl describe ingresses' },
  { command: 'kubectl describe endpoints' },
  { command: 'kubectl describe networkpolicies' },
  { command: 'kubectl describe pv' },
  { command: 'kubectl describe pvc' },
  { command: 'kubectl describe storageclasses' },
  { command: 'kubectl describe namespaces' },
  { command: 'kubectl describe events' },
  { command: 'kubectl describe serviceaccounts' },
  { command: 'kubectl describe roles' },
  { command: 'kubectl describe rolebindings' },
  { command: 'kubectl describe clusterroles' },
  { command: 'kubectl describe clusterrolebindings' },
  { command: 'kubectl describe crds' },
  // Describe commands with --all-namespaces
  { command: 'kubectl describe deployments --all-namespaces' },
  { command: 'kubectl describe pods --all-namespaces' },
  { command: 'kubectl describe services --all-namespaces' },
  { command: 'kubectl describe daemonsets --all-namespaces' },
  { command: 'kubectl describe statefulsets --all-namespaces' },
  { command: 'kubectl describe replicasets --all-namespaces' },
  { command: 'kubectl describe jobs --all-namespaces' },
  { command: 'kubectl describe cronjobs --all-namespaces' },
  { command: 'kubectl describe configmaps --all-namespaces' },
  { command: 'kubectl describe secrets --all-namespaces' },
  { command: 'kubectl describe resourcequotas --all-namespaces' },
  { command: 'kubectl describe limitranges --all-namespaces' },
  { command: 'kubectl describe hpa --all-namespaces' },
  { command: 'kubectl describe vpa --all-namespaces' },
  { command: 'kubectl describe ingresses --all-namespaces' },
  { command: 'kubectl describe endpoints --all-namespaces' },
  { command: 'kubectl describe networkpolicies --all-namespaces' },
  { command: 'kubectl describe pvc --all-namespaces' },
  { command: 'kubectl describe events --all-namespaces' },
  { command: 'kubectl describe serviceaccounts --all-namespaces' },
  { command: 'kubectl describe roles --all-namespaces' },
  { command: 'kubectl describe rolebindings --all-namespaces' },
 // Logs command (only for pods)
 // { command: 'kubectl logs <pod-name>' },
 // { command: 'kubectl logs <pod-name> -f' },
 ];